language: c
script: asdf plugin-test ninja https://github.com/aphecetche/asdf-ninja.git 'ninja --version'
before_script:
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh
os:
  - linux
  - osx
